### Post articles
POST http://localhost:3001/api/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViOTc2NjNiMmM4MzdlMjVjMTMyNmNmMyIsInVzZXJuYW1lIjoiY2hyaXNvbmdnIiwiZXhwIjoxNTQxODUxNDkwLCJpYXQiOjE1MzY2NzEwOTB9.NJr23SgU8SBpW80GNcbRKrvR2GCLbPwUpxcE0nKQSiM

{
  "article": {
    "title": "The Concept of Graphics",
    "description": "A comprehensive guide to graphical design",
    "body": "A comprehensive guide to graphical design",
    "tagList": ["graphics", "design", "web"],
    "favoritesCount": 1
  }
}

### Get article
GET http://localhost:3001/api/articles/the-concept-of-graphics-pz5wou

### Fetch all tags
GET http://localhost:3001/api/tags