### Register user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "user": {
    "username": "tes1ter",
    "email": "tester@coldmail.com",
    "password": "justAtest"
  }
}

### Good login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "ong.chris11@gmail.com",
    "password": "chrisongg_11"
  }
}

### Get token
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViYTA2MDQwYTZjNDRkMzU0NTk5ZDlkMyIsInVzZXJuYW1lIjoiY2hyaXNvbmdnIiwiZXhwIjoxNTQyNDE3NTAzLCJpYXQiOjE1MzcyMzcxMDN9.dmQVhwLbruh8aSDtkFyXfxW3kVK2la41v8uDKHBzQKA

{
  "payload": {
    "id": "5ba06040a6c44d354599d9d3"
  }
}

### Get profile
GET http://localhost:3001/api/profile/chrisongg

### Updating user details
PUT http://localhost:3000/api/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViOTc2NjNiMmM4MzdlMjVjMTMyNmNmMyIsInVzZXJuYW1lIjoiY2hyaXNvbmdnIiwiZXhwIjoxNTQyMjY1MjY4LCJpYXQiOjE1MzcwODQ4Njh9.Y7zA1Fk9yWOpz4-0ERVct_JeawUKejrZXCQw1dL2UgQ

{
  "user": {
    "username": "chrisongg",
    "email": "ong.chris11@gmail.com",
    "bio": "This is a test."
  }
}
